spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agenda2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: servicio-contactos
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/